<?php
/*
 *  Class ResetCacheTask
 * 
 *  Clear the SilverStripe cache (?mode=all) or only delete partial cache files 
 *  generated by the frontend (?mode=partial). Includes optional 
 *  testing only (&test=1) and verbose (&verbose=1) parameters
 * 
 *  Clicking the task in the taskmanager wil display info and a set 
 *  of prefab links 
 * 
 *  @author: Martimiz (martimiz at gmail dot com)
 */
class ResetCacheTask extends BuildTask {
  
	protected $title = 'to delete files from the SilverStripe cache';

	protected $description = 'Either remove only the frontend partial cache or empty the entire SilverStripe cache. Click this task for more info.';

	protected $currentURL;
 
	/**
	 *   Perform the task
	 */
	function run($request) {

		// Need Admin permission
		// @todo: point to login? No, don't wake sleeping dogs
		if (!Permission::check("ADMIN")) {
			echo "You need Administrator rights to perform this task!";
			return;
		}

		// Need to add mode=partial or mode=all (as an extra check)
		if (!isset($_GET['mode'])) {
			$this->currentURL = Director::absoluteBaseURL() . $request->getURL();
			$this->showHelp();
		} else { 

			if (isset($_GET['debug'])) self::$debug = true; 

			$mode       = $_GET['mode'];
			//$user       =  getTempFolderUsername(); 
			$tempfolder = getTempFolder();
			
			// determine the cache folder depending on the mode
			$cachefolder = ($mode == 'all')? $tempfolder : $tempfolder . '/cache/'; 

			if (!is_dir($tempfolder)) {
				echo "Couldn't find the cache in {$cachefolder}";
				return;
			} 
			
			// test only - show the files but do not actually delete them
			$test = (isset($_GET['test']))? true: false;

			// show the files that are deleted
			$verbose = (isset($_GET['verbose']))? true: false;

			// sub title for the running task
			$title = ($mode == 'partial')? 'Deleting partial frontend cache': 'Clearing the SilverStripe cache';
			if ($test) $title .= ' (test only)';
			echo "<h2>$title...</h2>";


			// (recursively) remove files and drectories. Skip . and .. folders and
			// start from the current folder downwards
			$files = new RecursiveIteratorIterator(
				new RecursiveDirectoryIterator($cachefolder, RecursiveDirectoryIterator::SKIP_DOTS),
				RecursiveIteratorIterator::CHILD_FIRST
			);
				 
			
			
			foreach ($files as $fileinfo) {
				
				$fileName = $fileinfo->getFilename();
				
				// partial mode needs filtering. Could extend the FilterIterator class - 
				// but that seems far too complex for this setup
				if ( $mode == 'all' || 
				    ($mode == 'partial' && stristr($fileName, 'zend_cache---cacheblock'))
				   ){

					// show file and irectorynames
					if ($verbose || $test) {
						if (!$test) echo "Removing: ";
						echo $fileinfo->getRealPath() . '<br>';
					}	

					$todo = ($fileinfo->isDir() ? 'rmdir' : 'unlink');

					// delete
					try {
						if (!$test) $todo($fileinfo->getRealPath());
					} catch (Exception $e) {
						echo '<br>Caught exception: ',  $e->getMessage(), "<br>";
					}
				}
			}
			
			echo "<br>READY<br>";
			
		}
	}
     
	
	protected function partialFilter($var) {	
		return (is_array($var) && preg_match("/^zend_cache---cacheblock/", $var));
	}
	
	
	
	/**
	 *   Provide basic instructions
	 */
	protected function showHelp() {
	    
		$help = <<<EOD
<h2>Description:</h2>
<p>
This task will delete the frontend partial cachefiles or completely clear the <br>
SilverStripe cache - depending on the 'mode' parameter: <br>
</p>
<ul>
	<li>?mode=partial - delete frontend partial cachefiles</li>
	<li>?mode=all - clear the SilverStripe cache
</ul>			
<p>
	Other optional parameters:
</p>	
<ul>
	<li>test=1 - show the filenames but do not delete the files</li>
	<li>verbose=1 - show the filenames while deleting the files</li>
</ul>			
<p>
	This task is provided by the author 'as is', there are no guaranties as to its <br>
	functioning properly, and the author will not accept any responsibility for <br>
	any damages resulting from executing this task.
</p>
<h2>Use these prefab links:</h2>
<ul>
	<li>
		<a href="{$this->currentURL}?mode=partial">Delete the frontend partial cachefiles</a> - 
		<a href="{$this->currentURL}?mode=partial&verbose=1">verbose</a> - 
		<a href="{$this->currentURL}?mode=partial&test=1">test only</a> 
	</li> 
	<li>
		<a href="{$this->currentURL}?mode=all">Completely clear the SilverStripe cache</a> - 
		<a href="{$this->currentURL}?mode=all&verbose=1">verbose</a> - 
		<a href="{$this->currentURL}?mode=all&test=1">test only</a>
	</li>
</ul>


EOD;
		echo $help; 
	}
}